ByteBank.Forum/ByteBank.Forum/Models/UsuarioAplicacao.cs
using Microsoft.AspNet.Identity.EntityFramework;

namespace ByteBank.Forum.Models
{
	public class UsuarioAplicacao : IdentityUser
	{
		public string NomeCompleto { get; set; }
	}
}

ByteBank.Forum/ByteBank.Forum/ViewModels/ContaRegistrarViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ByteBank.Forum.ViewModels
{
	public class ContaRegistrarViewModel
	{
		[Required]
		public string UserName { get; set; }

		[Required]
		[Display(Name ="Nome Completo")]
		public string NomeCompleto { get; set; }

		[Required]
		[EmailAddress]
		public string Email { get; set; }

		[Required]
		[DataType(DataType.Password)]
		public string Senha { get; set; }
	}
}

ByteBank.Forum/ByteBank.Forum/Controllers/ContaController.cs
using ByteBank.Forum.Models;
using ByteBank.Forum.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Host.SystemWeb;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Web.Mvc;
using System.Web;

namespace ByteBank.Forum.Controllers
{
	public class ContaController : Controller
	{
		private UserManager<UsuarioAplicacao> _userManager; //Backfield

		public UserManager<UsuarioAplicacao> UserManager
		{
			get
			{
				if (_userManager == null)
				{
					var contextoOwin = HttpContext.GetOwinContext();
				    _userManager = contextoOwin.GetUserManager<UserManager<UsuarioAplicacao>>();
				}
				return _userManager;
			}
			set
			{
				_userManager = value;
			}
		}
		public ActionResult Registrar()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Registrar(ContaRegistrarViewModel modelo)
		{
			if (ModelState.IsValid)
			{
				

				var novoUsuario = new UsuarioAplicacao();

				novoUsuario.UserName = modelo.UserName;
				novoUsuario.Email = modelo.Email;
				novoUsuario.NomeCompleto = modelo.NomeCompleto;

				UserManager.Create(novoUsuario, modelo.Senha);

				RedirectToAction("Index", "Home");
			}
			//algo errado devolvemos o modelo
			return View(modelo);
		}
	}
}

ByteBank.Forum/ByteBank.Forum/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ByteBank.Forum.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}
	}
}

ByteBank.Forum/ByteBank.Forum/Views/Conta/Registrar.cshtml
@model ByteBank.Forum.ViewModels.ContaRegistrarViewModel

@{
	ViewBag.Title = "Registrar";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Registrar</h2>
@using (Html.BeginForm())
{
	<h4>Complete o cadastro de sua conta!</h4>
	<hr />

	@Html.ValidationSummary("", new { @class = "text-danger" })
	@Html.EditorForModel()

	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="Registrar" class="btn btn-default"/>
		</div>
	</div>
}

ByteBank.Forum/ByteBank.Forum/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ByteBank.Forum/ByteBank.Forum/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ByteBank.Forum/ByteBank.Forum/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ByteBank.Forum/ByteBank.Forum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
				<ul class="navbar-right nav navbar-nav">
					<li>@Html.ActionLink("Registrar", "Registrar", "Conta")</li>
				</ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>